import Head from "next/head";
// internal imports
import Home from "@views/Home";
import { useEffect } from "react";
import { useGlobalContext } from "@context/context";

export default function HomePage({ exploreData }) {
  const { setExploreby } = useGlobalContext();
  useEffect(() => {
    setExploreby(exploreData);
  }, []);
  return (
    <div className="">
      <Head>
        <title>Airbnb Clone | Hasanul Haque Banna</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
    },
  };
}
