import Head from "next/head";
// internal imports
import Home from "@views/Home";
import { useEffect } from "react";
import { useGlobalContext } from "@context/context";

export default function HomePage({ exploreData }) {
  const { setData } = useGlobalContext();
  useEffect(() => {
    setData(exploreData);
  }, []);
  return (
    <div className="">
      <Head>
        <title>Airbnb Clone | Hasanul Haque Banna</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch(
    "https://jsonplaceholder.typicode.com/photos"
  ).then((res) => res.json());

  return {
    props: {
      exploreData,
    },
  };
}
